-- Why a verdict is what it is, as a word a reader can branch on.
--
-- **A `skipped` verdict has to say why, and prose cannot carry that.** A grader
-- narrowed to voice is skipped on a chat conversation; a threshold whose
-- measure the conversation never produced is skipped too. Both are correct and
-- neither is a failure, and a results page has to tell them apart — "this check
-- was never about this conversation" and "egma had nothing to measure" send a
-- reader to two different places.
--
-- The rationale beside it stays what it has always been: a line of prose
-- written to be read by a person, free to be reworded whenever it reads badly.
-- Putting a machine-readable reason inside that sentence would make its wording
-- contract, and the first person to improve it would break a page.
--
-- `LowCardinality(String)` with an empty default, so this is metadata only: no
-- part is rewritten, and every row already stored reads as having no stated
-- reason — which is exactly true of them. The column is not part of the sort
-- key and not part of a row's identity: two gradings of one dimension are still
-- one row, and the later one still wins, whatever either of them says here.
ALTER TABLE verdicts
    ADD COLUMN IF NOT EXISTS reason LowCardinality(String) DEFAULT '';
