-- The connection's type leaves the simulation row. A run reaches its agent
-- over exactly one connection, and the run header already holds that
-- connection's whole non-secret shape in `connection_snapshot` — which is
-- where every reader of a connection type takes one from. The per-simulation
-- copy was written out of the same object as the snapshot, in the same
-- transaction, and nothing ever read it back: a duplicate of a per-run fact,
-- stored per row, on the largest table there is.
--
-- `modality` stays, and the two columns are not one pattern. Modality is an
-- operand in the row's own check — `simulation_audio_facts_are_voice_facts`
-- refuses a measured band or a recording on a conversation that was not voice,
-- and a CHECK cannot join, so the column it compares has to sit on the row it
-- guards. Nothing about the connection type is guarded that way.
--
-- The constraint goes first, because a check cannot outlive the column it
-- names; and the pair goes together rather than one of them, because
-- `connection_type` without `simulation_connection_type_allowed` is
-- unconstrained text. What a connection may be is still checked where that is
-- the source of truth, by `connection_type_allowed` on `connection.type`.
ALTER TABLE "simulation" DROP CONSTRAINT "simulation_connection_type_allowed";--> statement-breakpoint
ALTER TABLE "simulation" DROP COLUMN "connection_type";