-- Per-test grader attachment is over: the junction leaves the schema.
--
-- **The rows were already gone.** `0026_running_copies` emptied this table
-- because every grader it pointed at was deleted with the type roster that
-- retired; this drops the table itself, which is the decision rather than the
-- consequence. A test names no graders, so a test version's content is the
-- scenario, the expected behaviors and the mock overrides, and nothing else.
--
-- What answers "which graders judge this simulation" instead is the project's
-- **running copies and their scope**: every active copy whose scope covers
-- simulations judges every simulation, and every copy scoped to production
-- judges production traffic. Where a grader applies is the grader's own
-- setting, asked once per grader, rather than a decision forced through the
-- content of every test that wanted it.
--
-- Nothing is lost that a project could not get back. Scenario-specific grading
-- returns as filters on the running copy — `{field, operator, values}` over
-- test and agent — in the custom-grader era, where one row on one grader says
-- what a junction row on every test used to.
--
-- `CASCADE` is drizzle's own wording and reaches nothing: this table's foreign
-- keys all point outwards, and no other object depends on it.
DROP TABLE "test_grader" CASCADE;
