/**
 * One test, as one markdown file in the developer's repository.
 *
 * The format is the whole point of the folder: a test somebody reviews in a
 * pull request has to read like something a person wrote. So the frontmatter
 * carries only what a machine needs — what the test is called, who calls, what
 * a connection has to be able to do, and the two tokens this file was last
 * synced at — and the body is the two things a test says, under the two
 * headings it says them under.
 *
 * ```markdown
 * ---
 * format: 3
 * name: missed-appointment-reschedule
 * description: The caller missed Thursday and wants any afternoon next week.
 * version: tstv_01K…
 * identity_revision: rev_01K…
 * required_capabilities: [dtmf]
 * personas:
 *   - id: prs_01K…
 *     name: Impatient customer
 * ---
 * ## Scenario
 * …prose…
 * ## Expected behaviors
 * 1. …ordered statements, each one a plain sentence…
 * ## Mock tools
 * …the tools this test answers for itself…
 * ```
 *
 * **Format 3 is a format rather than an edit, because two things that *defined*
 * format 2 are gone.** A statement carried a `[P0]`/`[P1]`/`[P2]` marker saying
 * how much it mattered, and the frontmatter carried `graders:`, the stable ids
 * of the graders that test added. The grader redesign retired both: every
 * expected behavior has to hold, so a per-sentence priority says nothing, and a
 * test names no graders at all — what judges a simulation is the project's
 * running graders and their own scope.
 *
 * **A format 2 file is read, not refused.** Both retirements are *ignored* on
 * read: a marker is stripped off the sentence it was written in front of, and
 * `graders:` is passed over. That is safe whether or not format 2 ever reached
 * a real repository, and it deliberately claims nothing about compatibility —
 * what `egma pull` should do to markers already sitting in somebody's git
 * history is a decision nobody has made yet.
 *
 * The third heading is there only when the test overrides one of the project's
 * mock tools. An override is test content — it versions with the test exactly
 * as an expected behavior does — which is why it lives in the test's own file
 * and not beside the project's.
 *
 * **Two tokens rather than one, because a test has two halves that move
 * independently.** `version:` is the content a run is judged by; `identity_
 * revision:` is the live half — the name and the description. Editing either in
 * the browser makes this copy stale, and each is refused on its own door, so a
 * colleague sharpening a scenario cannot refuse a one-word rename. Both are
 * absent on a file nothing has synced yet, and it is their presence that makes
 * the refusal rule checkable: without a pin there is nothing on the platform
 * this file claims to be a newer draft of.
 *
 * **A persona is named by identity, and the display name beside it is for the
 * reader.** The id is what a push resolves; a name somebody edits in the file
 * changes nothing about who calls, and a pull writes the platform's current
 * name back over it. Version-1 files carry only names, and those still resolve
 * — by name, on the platform, and only when exactly one active persona answers
 * to it.
 *
 * **Reading is forgiving and writing is exact.** These files are typed by
 * people and generated by coding agents, so a missing heading, a `-` list, a
 * lower-case heading, a behavior with no priority marker, and a persona written
 * as a bare name are all read rather than refused. Everything egma writes goes
 * out through the one serializer below, which is what makes `pull` immediately
 * after `push` change zero bytes.
 */

import {
  MOCK_TOOLS_LINE,
  readMockTools,
  writeMockTools,
  type MockToolEntry,
} from "./mock-tools.ts";
import {
  listAt,
  readYaml,
  sequenceAt,
  textAt,
  yamlFlowList,
  yamlScalar,
  type YamlMapping,
} from "./yaml.ts";

/**
 * The format this serializer writes, and the number a file says out loud.
 *
 * A number rather than a feature list, because the only readers are egma's own
 * two verbs and what they need to know is which shape the bytes are in. A file
 * that says nothing is format 1 — the shape that shipped first — and a file
 * that says a number egma has never heard of is read as generously as it can be
 * rather than refused, because refusing it would strand a folder that a newer
 * egma wrote and an older one is looking at. A format 2 file is read on exactly
 * those terms: see this module's own note for what is ignored in it.
 */
export const TEST_FILE_FORMAT = 3;

/**
 * One statement about what should happen — a plain sentence, and nothing else.
 *
 * It carried a priority in format 2 and it does not now. Every expected
 * behavior has to hold, so there was nothing left for a per-sentence marker to
 * say; how loudly a *grader* speaks is a setting on the grader.
 */
export type ExpectedBehavior = string;

/** One statement as a file wrote it down, which is the same shape. */
export type FileBehavior = string;

/**
 * One persona a test names: who they are on the platform, and what a reviewer
 * reads. The id is authoritative and the name is for the reader; a version-1
 * file carries only the name, and its id is empty until a pull writes one.
 */
export type FilePersona = {
  /** The `prs_` id, or empty on a file that has only ever carried names. */
  readonly id: string;
  /** What a reviewer reads. Refreshed by every pull. */
  readonly name: string;
};

/** What one file says. */
export type TestFile = {
  /** What the file itself claimed. Everything egma writes says 2. */
  readonly format: number;
  readonly name: string;
  /** Live metadata beside the name; `null` when the file names none. */
  readonly description: string | null;
  /** Named only when the situation demands one; empty takes the default. */
  readonly personas: readonly FilePersona[];
  /** The content version this file was last pulled or pushed at, or `null`. */
  readonly version: string | null;
  /** The live-half revision this file was last synced at, or `null`. */
  readonly identityRevision: string | null;
  /** What a connection has to be able to do for this test to mean anything. */
  readonly requiredCapabilities: readonly string[];
  /** The situation the agent is put in, as prose. */
  readonly scenario: string;
  /** In the order they were authored. */
  readonly expectedBehaviors: readonly FileBehavior[];
  /**
   * The tools this test answers for itself, overriding the project's for the
   * length of this test. Empty leaves the project's mock tools the whole world.
   */
  readonly mockTools: readonly MockToolEntry[];
};

export const SCENARIO_HEADING = "## Scenario";
export const EXPECTED_BEHAVIORS_HEADING = "## Expected behaviors";

/** Any of the three headings, however many hashes and in whatever case. */
const SCENARIO_LINE = /^#{1,6}\s*scenario\s*$/iu;
const EXPECTED_BEHAVIORS_LINE = /^#{1,6}\s*expected\s+behaviou?rs\s*$/iu;

/** `1. `, `1) `, `- ` or `* ` — the four ways a list gets typed. */
const LIST_ITEM = /^(?:\d+[.)]|[-*])\s+(.*)$/u;

/**
 * `[P1]` at the head of a statement, in whatever case it was typed.
 *
 * **Nothing writes one and this is the only thing that reads one.** It stays so
 * that a format 2 file — one already in somebody's repository, or one an older
 * egma wrote — is read rather than refused: the marker is stripped and the
 * sentence behind it is kept. Refusing would strand a folder over a word the
 * product has stopped having an opinion about.
 */
const PRIORITY_MARKER = /^\[\s*(p[012])\s*\]\s*(.*)$/iu;

function frontmatterOf(document: string, where: string): {
  readonly mapping: YamlMapping;
  readonly body: string;
} {
  // A document that does not open with the fence has no frontmatter, which is
  // what a hand-written first draft looks like. It is a body and nothing else.
  if (!/^---\s*\r?\n/u.test(document)) return { mapping: {}, body: document };

  const opened = document.slice(document.indexOf("\n") + 1);
  const close = opened.search(/^---\s*$/mu);
  if (close === -1) return { mapping: {}, body: document };

  const raw = opened.slice(0, close);
  const after = opened.slice(close);
  return {
    mapping: readYaml(raw, where),
    body: after.slice(after.indexOf("\n") + 1),
  };
}

/**
 * The body's three parts.
 *
 * The two headings after the scenario are the boundaries, so a scenario that
 * has headings of its own inside it keeps them. Anything before a scenario
 * heading — or a body with no heading at all — is read as the scenario, because
 * a file a person started typing is still a file egma should be able to push.
 *
 * Each boundary is the *last* heading of its kind and the scenario opens at the
 * *first* one, so a scenario whose prose quotes any of them keeps it. egma
 * writes each heading once, which makes first and last the same line in every
 * file egma has written.
 *
 * The mock tools heading is the one egma does not always write, so "the last
 * one" is not enough on its own: a test that overrides nothing and whose prose
 * quotes the heading has exactly one, and it is the prose's. What settles it is
 * the order egma writes the sections in — mock tools last — so the heading is
 * read as the section's only where it stands below the expected behaviors, and
 * anywhere above them it is prose the scenario keeps.
 */
function partsOf(body: string): {
  readonly scenario: string;
  readonly behaviors: string;
  readonly mockTools: readonly string[];
} {
  const lines = body.split("\n");
  const startsAt = lines.findIndex((line) => SCENARIO_LINE.test(line.trim()));
  const behaviorsAt = lines.findLastIndex((line) =>
    EXPECTED_BEHAVIORS_LINE.test(line.trim()),
  );
  const lastMockTools = lines.findLastIndex((line) => MOCK_TOOLS_LINE.test(line.trim()));
  const mockToolsAt = lastMockTools > behaviorsAt ? lastMockTools : -1;

  const from = startsAt === -1 ? 0 : startsAt + 1;
  const scenarioTo = Math.min(
    behaviorsAt === -1 ? lines.length : behaviorsAt,
    mockToolsAt === -1 ? lines.length : mockToolsAt,
  );
  const behaviorsTo = mockToolsAt === -1 ? lines.length : mockToolsAt;

  return {
    scenario: lines.slice(from, Math.max(from, scenarioTo)).join("\n").trim(),
    behaviors: behaviorsAt === -1 ? "" : lines.slice(behaviorsAt + 1, behaviorsTo).join("\n"),
    mockTools: mockToolsAt === -1 ? [] : lines.slice(mockToolsAt + 1),
  };
}

/**
 * The ordered list under the heading.
 *
 * A statement that wrapped onto a second line is one statement, so a line that
 * is not itself a list item joins the one above it. An empty list is read as an
 * empty list and never as a failure: a test with nothing to check is refused at
 * egma's door, in egma's own words, and reading it here is what lets it get
 * there to be refused.
 *
 * **A `[P0]` marker is stripped and the sentence behind it kept.** Format 2
 * wrote one on every line; nothing writes one now, and a file that still has
 * them is a file somebody's repository already holds. Reading it as the
 * sentence it always was is what lets that folder go on working.
 */
function behaviorsIn(text: string): readonly FileBehavior[] {
  const behaviors: string[] = [];
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (line === "") continue;
    const item = LIST_ITEM.exec(line);
    if (item !== null) {
      const said = (item[1] as string).trim();
      const marked = PRIORITY_MARKER.exec(said);
      behaviors.push(marked === null ? said : (marked[2] as string).trim());
      continue;
    }
    const last = behaviors.length - 1;
    if (last >= 0) behaviors[last] = `${behaviors[last] as string} ${line}`;
  }
  return behaviors.filter((one) => one !== "");
}

/**
 * The personas one file names, in the order it named them.
 *
 * Three shapes read, because three shapes get written: the version-2 sequence
 * of `id` and `name`, a bare name in that sequence, and the version-1 flow list
 * of names. What comes out is one shape, so nothing downstream has to know
 * which of the three it was reading.
 */
function personasIn(mapping: YamlMapping): readonly FilePersona[] {
  const found: FilePersona[] = [];
  for (const entry of sequenceAt(mapping, "personas")) {
    if (typeof entry === "string") {
      const name = entry.trim();
      if (name !== "") found.push({ id: "", name });
      continue;
    }
    const id = textAt(entry, "id") ?? "";
    const name = textAt(entry, "name") ?? "";
    if (id === "" && name === "") continue;
    found.push({ id, name });
  }
  return found;
}

/**
 * Read one file. `where` names it in anything this refuses.
 *
 * The name falls back to the file's own name when the frontmatter carries none,
 * because a file called `missed-appointment-reschedule.md` has already said what
 * it is called and refusing it would be pedantry.
 */
export function parseTestFile(
  document: string,
  where: string,
  fallbackName: string,
): TestFile {
  const { mapping, body } = frontmatterOf(document, where);
  const { scenario, behaviors, mockTools } = partsOf(body);
  const said = Number.parseInt(textAt(mapping, "format") ?? "", 10);

  return {
    format: Number.isNaN(said) ? 1 : said,
    name: textAt(mapping, "name") ?? fallbackName,
    description: textAt(mapping, "description"),
    personas: personasIn(mapping),
    version: textAt(mapping, "version"),
    identityRevision: textAt(mapping, "identity_revision"),
    // `graders:` is deliberately not read. It was format 2's stable ids of the
    // graders a test added, and a test names none now — so a file that still
    // carries the key is read past rather than refused, and pushing it names
    // no graders because there are none to name.
    requiredCapabilities: listAt(mapping, "required_capabilities"),
    scenario,
    expectedBehaviors: behaviorsIn(behaviors),
    mockTools: readMockTools(mockTools, where),
  };
}

/**
 * One expected behavior as the format holds it: one statement on one line.
 *
 * A statement that arrives with a line break in it is written as one line,
 * because that is the only shape the list has and it is exactly what reading
 * the file gives back — a line that is not itself a list item joins the one
 * above it with a space. Writing the break would mean the file said one thing
 * and read as another.
 */
function oneLine(behavior: string): string {
  return behavior.replaceAll(/\s+/gu, " ").trim();
}

/**
 * Write one file, in the one shape egma ever writes.
 *
 * Every byte here is decided by the value handed in, and nothing is carried over
 * from whatever the file held before. That is what makes the round trip stable:
 * `push` rewrites each file from what the platform stored, and a `pull` straight
 * afterwards computes the same bytes and finds nothing to do.
 *
 * The shape is the format's, not the value's, so what goes out is what reading
 * it gives back: no persona with nothing in it, no space wrapped around the
 * prose, and one statement per line. A value that cannot be written in that
 * shape is written in the nearest shape that can, rather than written in a way
 * that would read as something else.
 *
 * **No priority marker is written, on any line.** Format 2 wrote one on every
 * statement; the ladder retired, so there is nothing to write. A pull over a
 * folder holding format 2 files therefore rewrites each of them once, dropping
 * the markers and the `graders:` key — which is the ordinary shape of a format
 * change, and is why the number in the frontmatter moves with it.
 */
export function serializeTestFile(file: TestFile): string {
  const personas = file.personas.filter(
    (persona) => persona.id.trim() !== "" || persona.name.trim() !== "",
  );
  const frontmatter = [
    `format: ${String(TEST_FILE_FORMAT)}`,
    `name: ${yamlScalar(file.name)}`,
  ];
  if (file.description !== null && file.description.trim() !== "") {
    frontmatter.push(`description: ${yamlScalar(file.description)}`);
  }
  if (file.version !== null && file.version !== "") {
    frontmatter.push(`version: ${yamlScalar(file.version)}`);
  }
  if (file.identityRevision !== null && file.identityRevision !== "") {
    frontmatter.push(`identity_revision: ${yamlScalar(file.identityRevision)}`);
  }
  const capabilities = file.requiredCapabilities.filter((one) => one.trim() !== "");
  if (capabilities.length > 0) {
    frontmatter.push(`required_capabilities: ${yamlFlowList(capabilities)}`);
  }
  if (personas.length > 0) {
    frontmatter.push("personas:");
    for (const persona of personas) {
      // The id opens the entry because it is the one egma resolves. A persona
      // egma has no id for — a version-1 file nothing has pulled since — is
      // written as the name it was written with, and resolves by that name.
      const lines =
        persona.id.trim() === ""
          ? [`  - name: ${yamlScalar(persona.name)}`]
          : [
              `  - id: ${yamlScalar(persona.id)}`,
              ...(persona.name.trim() === ""
                ? []
                : [`    name: ${yamlScalar(persona.name)}`]),
            ];
      frontmatter.push(...lines);
    }
  }

  const scenario = file.scenario.trim();
  const behaviors = file.expectedBehaviors
    .map(oneLine)
    .filter((one) => one !== "")
    .map((one, index) => `${String(index + 1)}. ${one}`);

  return [
    "---",
    ...frontmatter,
    "---",
    SCENARIO_HEADING,
    ...(scenario === "" ? [] : [scenario]),
    EXPECTED_BEHAVIORS_HEADING,
    ...behaviors,
    // Last, and absent altogether on the ordinary test that overrides nothing:
    // a heading with nothing under it would read as a claim about a mocked
    // world this test does not make.
    ...writeMockTools(file.mockTools),
    "",
  ].join("\n");
}

/**
 * The file name a test is written under: its own name, in the shape a file name
 * can be. Two tests that reduce to the same name are told apart by the caller,
 * which is the only place that knows what else is in the folder.
 */
export function fileNameFor(name: string): string {
  const slug = name
    .normalize("NFKD")
    .replaceAll(/[^\p{Letter}\p{Number}]+/gu, "-")
    .replaceAll(/^-+|-+$/gu, "")
    .toLowerCase();
  return `${slug === "" ? "test" : slug}.md`;
}
