/**
 * One test, as one YAML file in the developer's repository.
 *
 * The format is the whole point of the folder: a test somebody reviews in a
 * pull request has to be readable at a glance, and what judges it has to be in
 * the same file as what it does. So one document carries both — the situation
 * the agent is put in, and the checks its conversation is judged against.
 *
 * ```yaml
 * name: missed-appointment-reschedule
 * personas: [impatient-caller]
 * version: tstv_01K…
 * scenario: |
 *   …prose…
 * expected_behaviors:
 *   - …one statement per line…
 * mock_tools:
 *   check_availability:
 *     answer:
 *       slots: []
 *     delay_ms: 250
 * ```
 *
 * **`expected_behaviors` is the grader.** Each statement is judged on its own
 * and comes back with its own verdict and the judge's written reason. That is
 * why they are a list of sentences and not prose: a paragraph is one thing to
 * argue with, and a list is one thing to argue with per line.
 *
 * `mock_tools` is there only when the test answers a tool for itself. An
 * override is test content — it versions with the test exactly as a behavior
 * does — which is why it lives here and not beside the project's.
 *
 * `version:` is absent on a file nothing has synced yet, and its presence is
 * what makes the refusal rule checkable: without a pin there is nothing on the
 * platform this file claims to be a newer draft of.
 *
 * **Reading is forgiving and writing is exact.** These files are typed by
 * people and generated by coding agents, so a scenario written as a plain
 * string, a behaviors list under either of two names, and a mock tool written
 * as a list rather than a mapping are all read rather than refused. Everything
 * egma writes goes out through the one serializer below, which is what makes
 * `pull` immediately after `push` change zero bytes.
 */

import { parse, stringify } from "yaml";

import type { MockToolEntry } from "./mock-tools.ts";

/** What one file says. */
export type TestFile = {
  readonly name: string;
  /** Named only when the situation demands one; empty takes the default. */
  readonly personas: readonly string[];
  /** The version this file was last pulled or pushed at, or `null`. */
  readonly version: string | null;
  /** The situation the agent is put in, as prose. */
  readonly scenario: string;
  /** In the order they were authored. Each one is judged on its own. */
  readonly expectedBehaviors: readonly string[];
  /**
   * The tools this test answers for itself, overriding the project's for the
   * length of this test. Empty leaves the project's mock tools the whole world.
   */
  readonly mockTools: readonly MockToolEntry[];
};

/** What the behaviors list may be called. The first is what egma writes. */
const BEHAVIOR_KEYS = ["expected_behaviors", "expectedBehaviors", "checks"] as const;

/** What the mock tools mapping may be called. The first is what egma writes. */
const MOCK_TOOL_KEYS = ["mock_tools", "mockTools"] as const;

/** A file egma could not read, said with enough to go and fix it. */
export class TestFileProblem extends Error {
  readonly where: string;

  constructor(where: string, said: string) {
    super(`${where}: ${said}`);
    this.name = "TestFileProblem";
    this.where = where;
  }
}

function mappingOf(value: unknown): Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

/**
 * Text at a key, however it was written.
 *
 * A number or a boolean is said back as itself rather than refused: somebody
 * who wrote `name: 2024` wrote a name, and a file egma cannot read is a file
 * nobody can push.
 */
function textAt(mapping: Record<string, unknown>, key: string): string | null {
  const held = mapping[key];
  if (typeof held === "string") return held.trim() === "" ? null : held;
  if (typeof held === "number" || typeof held === "boolean") return String(held);
  return null;
}

/** The first of these keys the file actually carries. */
function firstOf(
  mapping: Record<string, unknown>,
  keys: readonly string[],
): unknown {
  for (const key of keys) {
    if (mapping[key] !== undefined) return mapping[key];
  }
  return undefined;
}

/**
 * A list of statements, whatever shape it arrived in.
 *
 * A single string is one statement, because a file with one check is a file
 * somebody wrote in a hurry rather than a file that is wrong. Anything in the
 * list that is not text is left out rather than stringified into nonsense.
 */
function statementsIn(value: unknown): readonly string[] {
  if (typeof value === "string") {
    return value
      .split("\n")
      .map((line) => line.replace(/^\s*[-*]\s+/u, "").trim())
      .filter((line) => line !== "");
  }
  if (!Array.isArray(value)) return [];
  return value
    .flatMap((entry) => (typeof entry === "string" ? [entry.trim()] : []))
    .filter((entry) => entry !== "");
}

/** The personas a file names, in the order it named them. */
function personasIn(value: unknown): readonly string[] {
  if (typeof value === "string") return value.trim() === "" ? [] : [value.trim()];
  return statementsIn(value);
}

/**
 * The mock tools a file carries.
 *
 * Written as a mapping of tool name to what it answers with, which is the
 * shape that reads best and the only shape egma writes. A list of entries each
 * naming its own tool is read too, because that is the other way somebody
 * naturally writes it.
 */
function mockToolsIn(value: unknown, where: string): readonly MockToolEntry[] {
  if (value === undefined || value === null) return [];

  if (Array.isArray(value)) {
    return value.flatMap((entry) => {
      const held = mappingOf(entry);
      const { tool, ...says } = held;
      const named = typeof tool === "string" ? tool.trim() : "";
      return named === "" ? [] : [{ tool: named, says }];
    });
  }

  const mapping = mappingOf(value);
  return Object.entries(mapping).flatMap(([tool, says]) => {
    const named = tool.trim();
    if (named === "") return [];
    if (typeof says !== "object" || says === null || Array.isArray(says)) {
      throw new TestFileProblem(
        where,
        `the mock tool "${named}" says ${JSON.stringify(says)}, and a mock tool ` +
          `is written as what it answers with — like answer: {slots: []} or ` +
          `error: the calendar is unreachable.`,
      );
    }
    return [{ tool: named, says: says as Record<string, unknown> }];
  });
}

/**
 * Read one file. `where` names it in anything this refuses.
 *
 * The name falls back to the file's own name when the document carries none,
 * because a file called `missed-appointment-reschedule.yaml` has already said
 * what it is called and refusing it would be pedantry.
 */
export function parseTestFile(
  document: string,
  where: string,
  fallbackName: string,
): TestFile {
  let read: unknown;
  try {
    read = parse(document);
  } catch (problem) {
    throw new TestFileProblem(
      where,
      `this is not YAML egma can read — ${
        problem instanceof Error ? problem.message : String(problem)
      }`,
    );
  }

  // An empty file is an empty test rather than a failure: a file somebody has
  // started is still a file egma should be able to name and hold back.
  const mapping = mappingOf(read);

  return {
    name: textAt(mapping, "name") ?? fallbackName,
    personas: personasIn(mapping.personas),
    version: textAt(mapping, "version"),
    scenario: (textAt(mapping, "scenario") ?? "").trim(),
    expectedBehaviors: statementsIn(firstOf(mapping, BEHAVIOR_KEYS)),
    mockTools: mockToolsIn(firstOf(mapping, MOCK_TOOL_KEYS), where),
  };
}

/**
 * One expected behavior as the format holds it: one statement on one line.
 *
 * A statement that arrives with a line break in it is written as one line,
 * because that is the only shape the list has and it is exactly what reading
 * the file gives back. Writing the break would mean the file said one thing and
 * read as another.
 */
function oneLine(behavior: string): string {
  return behavior.replaceAll(/\s+/gu, " ").trim();
}

/**
 * Write one file, in the one shape egma ever writes.
 *
 * Every byte here is decided by the value handed in, and nothing is carried
 * over from whatever the file held before. That is what makes the round trip
 * stable: `push` rewrites each file from what the platform stored, and a `pull`
 * straight afterwards computes the same bytes and finds nothing to do.
 *
 * The key order is the order a person reads them in — what this is called, who
 * calls, what happens, what must be true, and last the mocked world — and it is
 * fixed here rather than left to whatever order a value's keys happen to be in.
 */
export function serializeTestFile(file: TestFile): string {
  const personas = file.personas.filter((persona) => persona.trim() !== "");
  const behaviors = file.expectedBehaviors
    .map(oneLine)
    .filter((behavior) => behavior !== "");

  const document: Record<string, unknown> = { name: file.name };
  if (personas.length > 0) document.personas = personas;
  if (file.version !== null && file.version !== "") document.version = file.version;

  // Always written, even empty. The scenario and the checks are what a test is,
  // and a file that left one out would read as a file somebody had not finished
  // rather than a test that says nothing.
  document.scenario = file.scenario.trim();
  document.expected_behaviors = behaviors;

  // Last, and absent altogether on the ordinary test that overrides nothing: a
  // key with nothing under it would read as a claim about a mocked world this
  // test does not make.
  if (file.mockTools.length > 0) {
    document.mock_tools = Object.fromEntries(
      file.mockTools.map((entry) => [entry.tool, entry.says]),
    );
  }

  return stringify(document, {
    // Prose is written as a block, so a scenario reads as the paragraph
    // somebody wrote rather than as one very long quoted line.
    blockQuote: "literal",
    lineWidth: 0,
    indent: 2,
    // A list sits under its key rather than beside it, which is what everybody
    // writing YAML by hand does.
    indentSeq: true,
  });
}

/**
 * The file name a test is written under: its own name, in the shape a file name
 * can be. Two tests that reduce to the same name are told apart by the caller,
 * which is the only place that knows what else is in the folder.
 */
export function fileNameFor(name: string): string {
  const slug = name
    .normalize("NFKD")
    .replaceAll(/[^\p{Letter}\p{Number}]+/gu, "-")
    .replaceAll(/^-+|-+$/gu, "")
    .toLowerCase();
  return `${slug === "" ? "test" : slug}.yaml`;
}
