/**
 * One test, as one markdown file in the developer's repository.
 *
 * The format is the whole point of the folder: a test somebody reviews in a
 * pull request has to read like something a person wrote. So the frontmatter
 * carries only what a machine needs — the name, who calls, and the version this
 * file was last synced at — and the body is the two things a test says, under
 * the two headings it says them under.
 *
 * ```markdown
 * ---
 * name: missed-appointment-reschedule
 * personas: [impatient-caller]
 * version: tstv_01K…
 * ---
 * ## Scenario
 * …prose…
 * ## Expected behaviors
 * 1. …ordered statements…
 * ```
 *
 * `version:` is absent on a file nothing has synced yet, and its presence is
 * what makes the refusal rule checkable: without a pin there is nothing on the
 * platform this file claims to be a newer draft of.
 *
 * **Reading is forgiving and writing is exact.** These files are typed by
 * people and generated by coding agents, so a missing heading, a `-` list, or a
 * lower-case heading are all read rather than refused. Everything egma writes
 * goes out through the one serializer below, which is what makes `pull`
 * immediately after `push` change zero bytes.
 */

import {
  listAt,
  readYaml,
  textAt,
  yamlFlowList,
  yamlScalar,
  type YamlMapping,
} from "./yaml.ts";

/** What one file says. */
export type TestFile = {
  readonly name: string;
  /** Named only when the situation demands one; empty takes the default. */
  readonly personas: readonly string[];
  /** The version this file was last pulled or pushed at, or `null`. */
  readonly version: string | null;
  /** The situation the agent is put in, as prose. */
  readonly scenario: string;
  /** In the order they were authored. */
  readonly expectedBehaviors: readonly string[];
};

export const SCENARIO_HEADING = "## Scenario";
export const EXPECTED_BEHAVIORS_HEADING = "## Expected behaviors";

/** Either heading, however many hashes and whatever case it was written in. */
const SCENARIO_LINE = /^#{1,6}\s*scenario\s*$/iu;
const EXPECTED_BEHAVIORS_LINE = /^#{1,6}\s*expected\s+behaviou?rs\s*$/iu;

/** `1. `, `1) `, `- ` or `* ` — the four ways a list gets typed. */
const LIST_ITEM = /^(?:\d+[.)]|[-*])\s+(.*)$/u;

function frontmatterOf(document: string, where: string): {
  readonly mapping: YamlMapping;
  readonly body: string;
} {
  // A document that does not open with the fence has no frontmatter, which is
  // what a hand-written first draft looks like. It is a body and nothing else.
  if (!/^---\s*\r?\n/u.test(document)) return { mapping: {}, body: document };

  const opened = document.slice(document.indexOf("\n") + 1);
  const close = opened.search(/^---\s*$/mu);
  if (close === -1) return { mapping: {}, body: document };

  const raw = opened.slice(0, close);
  const after = opened.slice(close);
  return {
    mapping: readYaml(raw, where),
    body: after.slice(after.indexOf("\n") + 1),
  };
}

/**
 * The body's two parts.
 *
 * The expected-behaviors heading is the one boundary, so a scenario that has
 * headings of its own inside it keeps them. Anything before a scenario heading
 * — or a body with no heading at all — is read as the scenario, because a file
 * a person started typing is still a file egma should be able to push.
 *
 * The boundary is the *last* heading and the scenario opens at the *first* one,
 * so a scenario whose prose quotes either heading keeps it. egma writes each
 * heading once, which makes first and last the same line in every file egma
 * has written.
 */
function partsOf(body: string): { readonly scenario: string; readonly behaviors: string } {
  const lines = body.split("\n");
  const startsAt = lines.findIndex((line) => SCENARIO_LINE.test(line.trim()));
  const boundary = lines.findLastIndex((line) => EXPECTED_BEHAVIORS_LINE.test(line.trim()));

  const from = startsAt === -1 ? 0 : startsAt + 1;
  const to = boundary === -1 ? lines.length : boundary;
  return {
    scenario: lines.slice(from, Math.max(from, to)).join("\n").trim(),
    behaviors: boundary === -1 ? "" : lines.slice(boundary + 1).join("\n"),
  };
}

/**
 * The ordered list under the heading.
 *
 * A statement that wrapped onto a second line is one statement, so a line that
 * is not itself a list item joins the one above it. An empty list is read as an
 * empty list and never as a failure: a test with nothing to check is refused at
 * egma's door, in egma's own words, and reading it here is what lets it get
 * there to be refused.
 */
function behaviorsIn(text: string): readonly string[] {
  const behaviors: string[] = [];
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (line === "") continue;
    const item = LIST_ITEM.exec(line);
    if (item !== null) {
      behaviors.push((item[1] as string).trim());
      continue;
    }
    const last = behaviors.length - 1;
    if (last >= 0) behaviors[last] = `${behaviors[last] as string} ${line}`;
  }
  return behaviors.filter((behavior) => behavior !== "");
}

/**
 * Read one file. `where` names it in anything this refuses.
 *
 * The name falls back to the file's own name when the frontmatter carries none,
 * because a file called `missed-appointment-reschedule.md` has already said what
 * it is called and refusing it would be pedantry.
 */
export function parseTestFile(
  document: string,
  where: string,
  fallbackName: string,
): TestFile {
  const { mapping, body } = frontmatterOf(document, where);
  const { scenario, behaviors } = partsOf(body);

  return {
    name: textAt(mapping, "name") ?? fallbackName,
    personas: listAt(mapping, "personas"),
    version: textAt(mapping, "version"),
    scenario,
    expectedBehaviors: behaviorsIn(behaviors),
  };
}

/**
 * One expected behavior as the format holds it: one statement on one line.
 *
 * A statement that arrives with a line break in it is written as one line,
 * because that is the only shape the list has and it is exactly what reading
 * the file gives back — a line that is not itself a list item joins the one
 * above it with a space. Writing the break would mean the file said one thing
 * and read as another.
 */
function oneLine(behavior: string): string {
  return behavior.replaceAll(/\s+/gu, " ").trim();
}

/**
 * Write one file, in the one shape egma ever writes.
 *
 * Every byte here is decided by the value handed in, and nothing is carried over
 * from whatever the file held before. That is what makes the round trip stable:
 * `push` rewrites each file from what the platform stored, and a `pull` straight
 * afterwards computes the same bytes and finds nothing to do.
 *
 * The shape is the format's, not the value's, so what goes out is what reading
 * it gives back: no persona with nothing in it, no space wrapped around the
 * prose, and one statement per line. A value that cannot be written in that
 * shape is written in the nearest shape that can, rather than written in a way
 * that would read as something else.
 */
export function serializeTestFile(file: TestFile): string {
  const personas = file.personas.filter((persona) => persona.trim() !== "");
  const frontmatter = [`name: ${yamlScalar(file.name)}`];
  if (personas.length > 0) {
    frontmatter.push(`personas: ${yamlFlowList(personas)}`);
  }
  if (file.version !== null && file.version !== "") {
    frontmatter.push(`version: ${yamlScalar(file.version)}`);
  }

  const scenario = file.scenario.trim();
  const behaviors = file.expectedBehaviors
    .map(oneLine)
    .filter((behavior) => behavior !== "")
    .map((behavior, index) => `${index + 1}. ${behavior}`);

  return [
    "---",
    ...frontmatter,
    "---",
    SCENARIO_HEADING,
    ...(scenario === "" ? [] : [scenario]),
    EXPECTED_BEHAVIORS_HEADING,
    ...behaviors,
    "",
  ].join("\n");
}

/**
 * The file name a test is written under: its own name, in the shape a file name
 * can be. Two tests that reduce to the same name are told apart by the caller,
 * which is the only place that knows what else is in the folder.
 */
export function fileNameFor(name: string): string {
  const slug = name
    .normalize("NFKD")
    .replaceAll(/[^\p{Letter}\p{Number}]+/gu, "-")
    .replaceAll(/^-+|-+$/gu, "")
    .toLowerCase();
  return `${slug === "" ? "test" : slug}.md`;
}
